#+TITLE: Windows 10 Setup
#+AUTHOR: James Blair
#+EMAIL: mail@jamesblair.net
#+DATE: 1st September 2019


* Install windows subsystem for linux

  To get underway we need to enable [[https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux][wsl]].  This requires a 64bit installation
  of Windows 10.

  #+NAME: Enable the wsl feature
  #+BEGIN_SRC tmate
  powershell.exe Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
  #+END_SRC


  After enabling the wsl feature we need to download the debian installer and
  open it.

  #+NAME: Download the debian installer
  #+BEGIN_SRC tmate
  cd "C:\Users\jmhbnz\Downloads"
  powershell.exe curl.exe -L -o debian.appx https://aka.ms/wsl-debian-gnulinux
  powershell.exe Add-AppxPackage .\debian.appx
  #+END_SRC

  
  After the installer runs we need to manually enter a username and password for
  the unix account that wsl will use.


* Configure windows ten

  Enable all tray icons to be visible and restart explorer
  
  #+NAME: Configure tray icons
  #+BEGIN_SRC tmate
  powershell.exe Set-ItemProperty HKLM:\SOFTWARE\Micorosoft\Windows\CurrentVersion\Explorer EnableAutoTray 0  
  powershell.exe ps explorer | kill
  #+END_SRC

  Additionally I normally take the following actions:

** Update taskbar layout

   - Hide the search box.
   - Hide the task view button.
   - Unpin all but explorer.


** Update start menu layout

   - Unpin all applications from start.


** Lock screen configuration

   - Untick show tips
   - Set background to be picture and use in folder
   - Remove status detailed or otherwise for apps on lock screen


** Fix inactive window title colors

   https://winaero.com/blog/change-color-of-inactive-title-bars-in-windows-10/  
